#!/usr/bin/env bash
source Setup_Base_Test.sh
cd ../../..
source Run_Flask.sh
python3 registration_test.py
python3 login_test.py
python3 navigation_bar_test.py
python3 ticket_type_test.py
python3 time_select_test.py
source Rest_Api_Test.sh
